---
apiVersion: v1
kind: Namespace
metadata:
    name: cloudnative-webapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-host-configmaps
  namespace: cloudnative-webapp
data:
  mysql-host: "<input mysql host IP here>"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cloudnative-webapp
type: Opaque
stringData:
  mysql-database: <input database name>
  mysql-user: <input mysql username>
  mysql-password: <input mysql password>
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cloudnative-webapp
  labels:
    tier: app
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: php
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cloudnative-webapp
  labels:
    tier: web
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "15"
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cloudnative-webapp
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: app
  template:
    metadata:
      labels:
        app: php
        tier: app
    spec:
      containers:
      - name: php
        image: <region_key>.ocir.io/<tenancy_namespace>/webapp/php:1.0
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.25"
          limits:
            memory: "200Mi"
            cpu: "0.5"
        ports:
        - containerPort: 9000
        env:
        - name: MDS_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-host-configmaps
              key: mysql-host
        - name: MDS_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: MDS_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cloudnative-webapp
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: <region_key>.ocir.io/<tenancy_namespace>/webapp/nginx:1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.25"
          limits:
            memory: "200Mi"
            cpu: "0.5"
---